#!/bin/sh
# Generate C header with embedded asset data from input files.
# Usage: embed.sh file1 file2 ... > embed_assets.h

echo "// Auto-generated by scripts/embed.sh -- do not edit"
echo "#ifndef EMBED_ASSETS_H"
echo "#define EMBED_ASSETS_H"
echo ""

for f in "$@"; do
    base=$(basename "$f")
    name="embed_$(echo "$base" | sed 's/[-.]/_/g')"

    if echo "$f" | grep -q '\.svg$'; then
        # SVG: embed as C string (null-terminated)
        echo "static const unsigned char ${name}[] ="
        sed 's/\\/\\\\/g; s/"/\\"/g; s/^/    "/; s/$/\\n"/' "$f"
        echo "    \"\\0\";"
        size=$(wc -c < "$f")
        size=$((size + 1))
        echo "static const unsigned int ${name}_len = ${size};"
    else
        # Binary: use xxd
        echo "static const unsigned char ${name}[] = {"
        xxd -i < "$f"
        echo "};"
        size=$(wc -c < "$f")
        echo "static const unsigned int ${name}_len = ${size};"
    fi
    echo ""
done

echo "#endif // EMBED_ASSETS_H"
